Fixed Spacing in Path Bug on Windows
GatorEducator/execexam pull request #41
Opened 2024-10-28 02:22 UTC by TitusSmith33

# Pull Request

Contributors: Titus Smith

This PR is aimed at fixing Issue #36, which causes a stack trace on Windows 11 when running `execexam` if a space exists anywhere in the directory path.

This PR simply changes 1 line that is passed in `main.py` of `execexam` when the path to a failing check is passed. Symbax previously handled paths separately if there was a space anywhere in the directory. For example, if you had the following path:
`user/documents/software engineering/exam_solution` the program was splitting the path and trying to handle them one at a time rather than as one. This PR makes sure the failing path is quoted properly so that paths are handled as one, regardless of whether a space exists. 

This PR should not affect code coverage.

This PR was created and tested on a Windows 11 OS. I have tested this new implementation with a space in my path, and with no spaces in my path, and they both pass without causing a stack trace anymore.

Below is line 288 of `main.py`, which is where I changed how paths are handled:

```python
command = f'symbex {test_name}" -f "{failing_test_path}"'
```

2024-10-30 12:16 UTC, gkapfham commented
Hello @TitusSmith33 can you please move this PR forward through the review process? We need to get a review from one student technical leader and from two students who did not work on the fix. Thanks, I appreciate your contribution and your work in moving this PR through the process.

2024-10-31 15:44 UTC, Chezka109 approved these changes
Tested it out on MacOS and it's all good! I added a space in a solution repo and did not get a stack trace.

2024-10-31 18:50 UTC, hannahb09 approved these changes
I got it to run on linux. I added a space and there was no error for it.

2024-10-31 18:52 UTC, AlishChhetri approved these changes
LGTM!

2024-10-31 19:44 UTC, CalebKendra approved these changes

2024-11-05 18:01 UTC, PCain02 approved these changes
It worked for me on Windows 10! LGTM

2024-11-13 14:02 UTC, gkapfham commented
Hello @TitusSmith33 will you need to update your pyproject.toml file?

2024-11-21 02:07 UTC, PCain02 requested changes
@TitusSmith33  it says there are still conflicts with the `pyproject.toml`. You may have to literally hit the button that says mark as resolved after you have fixed the conflicts. You can see the resolve conflicts button under "changes approved"

2024-11-22 15:21 UTC, boulais01 approved these changes
LGTM, it would appear you have updated and resolved the changes requested.

2024-11-26 00:36 UTC, PCain02 approved these changes
LGTM Thank you for updating the `pyproject.toml ` file. Note you can add your name to the authors if you want.

2024-12-05 19:40 UTC, CalebKendra approved these changes
LGTM

2025-01-22 18:08 UTC, merged